---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:

  run-mvn-build:
    name: ${{ matrix.distribution }} ${{ matrix.version }} (jdk-x64) - ${{ matrix.os }} - Run mvn build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        distribution: [ 'adopt', 'zulu' ] # internally 'adopt-hotspot' is the same as 'adopt'
        version: [ '8', '11' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.version }}
          distribution: ${{ matrix.distribution }}
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
